### PR TITLE
fix CFLAGS key in dict.

### PR DESCRIPTION
**Pull request by ahmubashshir**
CFLAGS wasn't getting added to the dict.This would fix the problem

### CODE REVIEW

**Comment by anntzer** [comment]
At least locally CFLAGS are already correctly collected; can you clarify the circumstances where your patch is needed?

**Comment by ahmubashshir** [comment]
As the `get_makepkg_conf()` method splits keys by '\0', adding '\0' before 'CFLAGS' will add it to dict no matter what.

**Comment by anntzer** [comment]
Again, please provide a repro.
```
$ python -c 'from pypi2pkgbuild import get_makepkg_conf; print(get_makepkg_conf())'
{'CFLAGS': '-march=native -O2 -pipe -fstack-protector-strong -fno-plt', 'CXXFLAGS': '-march=native -O2 -pipe -fstack-protector-strong -fno-plt', 'PACKAGER': 'Antony Lee <anntzer.lee@gmail.com>'}
```

**Comment by ahmubashshir** [comment]
The previous implementation of get_makepkg_conf used file redrection in makepkg.  
But this implementation works without redirecting to a file.

**Comment by anntzer** [comment]
The point of file redirection is to avoid the rest of the log printed by makepkg.  Yes putting an additional \0 in the front also works, but we have no guarantees that makepkg won't start outputting additional \0's.
pypi2pkgbuild already spaws tons of subprocesses anyways, so it's not as if saving a redirect would really change improve the perf.

**Pull request closed without merging**
